version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_ENVIRONMENT=development
    volumes:
      - ./src:/app
    networks:
      - jeycentre-network

volumes:
  static_volume:

networks:
  jeycentre-network:
    driver: bridge
