# Generated by Django 5.2.6 on 2025-09-07 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCodeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=20)),
                ("issued_at", models.DateTimeField()),
                (
                    "qr_type",
                    models.CharField(
                        choices=[("checkin", "Check-in")],
                        default="checkin",
                        max_length=20,
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="True if QR code was successfully used"
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "QR Code Log",
                "verbose_name_plural": "QR Code Logs",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(help_text="Attendance date (YYYY-MM-DD)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("did_not_checkout", "Did Not Checkout"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                (
                    "checkin_status",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("very_late", "Very Late"),
                            ("no_data", "No Data"),
                        ],
                        default="no_data",
                        max_length=20,
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total working hours",
                        max_digits=4,
                    ),
                ),
                (
                    "needs_checkout_correction",
                    models.BooleanField(
                        default=False, help_text="True if employee forgot to checkout"
                    ),
                ),
                (
                    "auto_checkout",
                    models.BooleanField(
                        default=False,
                        help_text="True if system performed auto-checkout",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Log",
                "verbose_name_plural": "Attendance Logs",
                "ordering": ["-date", "employee"],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="CheckoutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_checkout_time",
                    models.TimeField(help_text="Time when employee claims they left"),
                ),
                ("reason", models.TextField(help_text="Reason for missing checkout")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("supervisor_notes", models.TextField(blank=True)),
                (
                    "attendance_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_requests",
                        to="attendance.attendancelog",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        limit_choices_to={"role": "supervisor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervised_checkout_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        limit_choices_to={"role": "therapist"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkout Request",
                "verbose_name_plural": "Checkout Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("casual_leave", "Casual Leave"),
                            ("unpaid_leave", "Unpaid Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "leave_days",
                    models.IntegerField(help_text="Total number of leave days"),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "month_year",
                    models.CharField(
                        help_text="Month-Year for CL tracking (YYYY-MM)", max_length=7
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "role__in": ["supervisor", "hr", "superadmin"]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Application",
                "verbose_name_plural": "Leave Applications",
                "ordering": ["-applied_at"],
            },
        ),
    ]
