# Generated by Django 5.2.6 on 2025-09-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendancelog",
            unique_together=set(),
        ),
    ]
