# Generated by Django 5.2.6 on 2025-09-08 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendancelog_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(
                fields=["employee", "date"], name="attendance__employe_83a268_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(fields=["date"], name="attendance__date_bddb55_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(fields=["status"], name="attendance__status_018901_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(
                fields=["employee", "-date"], name="attendance__employe_9bfc47_idx"
            ),
        ),
    ]
