# Generated by Django 5.2.6 on 2025-09-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_accounts_cu_branch__c3322e_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customuser",
            name="accounts_cu_is_acti_2885e2_idx",
        ),
    ]
