# Generated by Django 5.2.6 on 2025-09-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="is_active",
        ),
    ]
